services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  db:
    container_name: db-container
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: microchirp
      POSTGRES_USER: microchirp
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    
  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_API_PROXY=http://backend:8000
    depends_on:
      - backend

volumes:
  postgres_data: